# file: .github/workflows/say-hello.yml
name: say-hello
# on – определяет события, которые запускают воркфлоу
on: push
jobs:
  # build – произвольно выбранное имя задания
  # их может быть больше одного
  build:
    # операционная система для работы воркфлоу
    runs-on: ubuntu-latest
    steps: # список шагов, которые надо выполнить
      # экшен — выполняет какую-то задачу
      # checkout — клонирует репозиторий
      - uses: actions/checkout@v4
      # Устанавливаем Node.js
      - uses: actions/setup-node@v4
      # run – произвольная bash-команда
      - run: npm install
      #- run: npm test
      #- run: npm run lint
      # ls -la выведет содержимое текущего репозитория
      - run: make say-hello

